# Generated by Django 6.0 on 2026-01-03 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
