# Generated by Django 6.0 on 2026-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mycontact_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name=50)),
            ],
        ),
    ]
