# Generated by Django 6.0 on 2026-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
