# Generated by Django 6.0 on 2026-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_myusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
