# Generated by Django 6.0 on 2026-01-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_mycontact_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycontact',
            name='banner',
        ),
    ]
