# Generated by Django 6.0 on 2026-01-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mycontact_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='banner',
            field=models.ImageField(blank=True, default='logo.png', upload_to='media/'),
        ),
    ]
